# fly.toml app configuration file generated for codex-app on 2023-07-03T20:25:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codex-app"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
